global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'server1'
    metrics_path: "/prometheus"
    static_configs:
      - targets: [ '159.65.253.86:9000' ]

  - job_name: 'server2'
    metrics_path: "/prometheus"
    static_configs:
      - targets: [ '167.99.60.112:9000' ]

  - job_name: 'server3'
    metrics_path: "/prometheus"
    static_configs:
      - targets: [ '159.65.247.200:9000' ]
